### ISSUE TITLE
testLocal -s fails (ERR_MULTIPLE_CALLBACK)

### ISSUE THREAD

**Issue by agamm** [c6fc/warcannon#18]
I tried running it multiple times, but it always fails here. My match.js:
```
"use strict";

exports.mime_types = [
  "text/html",
];

exports.domains = [];

exports.regex_patterns = {
  derp: />[\s]*submit[\s]*</ig,
};

// custom functions are executed against regex matches of the associated key.
// A return value of boolean false will be discarded from further processing.
exports.custom_functions = {
};
```
I get:
```
{ type: 'progress', recordcount: 118571, recordsprocessed: 31373 }
{ type: 'progress', recordcount: 119450, recordsprocessed: 31649 }
{ type: 'progress', recordcount: 120384, recordsprocessed: 31921 }
{ type: 'progress', recordcount: 121442, recordsprocessed: 32231 }
{ type: 'progress', recordcount: 122309, recordsprocessed: 32463 }
{ type: 'progress', recordcount: 123460, recordsprocessed: 32784 }
{ type: 'progress', recordcount: 124616, recordsprocessed: 33119 }
Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times
    at NodeError (node:internal/errors:371:5)
    at onFinish (node:internal/streams/writable:668:37)
    at node:internal/streams/transform:128:9
    at WARCStreamTransform._flush (/aws/mde/warcannon/lambda_functions/warcannon/node_modules/node-warc/lib/parsers/warcStreamTransform.js:114:5)
    at WARCStreamTransform.final [as _final] (node:internal/streams/transform:112:25)
    at callFinal (node:internal/streams/writable:695:27)
    at prefinish (node:internal/streams/writable:720:7)
    at finishMaybe (node:internal/streams/writable:730:5)
    at WARCStreamTransform.Writable.end (node:internal/streams/writable:632:5)
    at Yallist.<anonymous> (/aws/mde/warcannon/lambda_functions/warcannon/node_modules/minipass/index.js:409:18) {
  code: 'ERR_MULTIPLE_CALLBACK'
}
```

**Comment by c6fc** [comment]
Also, feel free to join the discord channel for faster response.

**Comment by agamm** [comment]
> That's a bug with a particular version of NodeJS. The same bug that was fixed by pinning a specific version in your earlier issue. Use NodeJS version 16.4.2, and the issue will clear.

This is after I used the `dev` branch.

**Comment by agamm** [comment]
I just use `warcannon test` now.
